# Generated by Django 3.2.19 on 2023-07-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact-Us'},
        ),
    ]
