from django import forms
from .models import UserProfile


class UserProfileForm(forms.ModelForm):
    """
    Create the layout of the Order Form
    """

    class Meta:
        model = UserProfile
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove autogenerated labels and
        set autofocus to first form field
        """

        super().__init__(*args, **kwargs)
        placeholders = {
            'default_phone_number': 'Phone Number',
            'default_country': 'Country',
            'default_post_code': 'Postcode',
            'default_town_or_city': 'Town or City',
            'default_address_line1': 'Address Line 1',
            'default_address_line2': 'Address Line 2',
            'default_county': 'County or State',
        }

        self.fields['default_phone_number'].widget.attrs['autofocus'] = True
        # Set an asterix on required fields, and placeholder on all fields
        for field in self.fields:
            if field != 'default_country':
                if self.fields[field].required:
                    placeholder = f'{placeholders[field]} *'
                else:
                    placeholder = placeholders[field]
                self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].widget.attrs['class'] = 'border-dark rounded-0'
            self.fields[field].label = False
