# Generated by Django 3.2.19 on 2023-06-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebuiltpc',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
