# Generated by Django 3.2.19 on 2023-06-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_prebuiltpc_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
